export const FETCH_PRICECONSUMER_REQUEST =
  'priceconsumer.FETCH_PRICECONSUMER_REQUEST';
export const FETCH_PRICECONSUMER_SUCCESS =
  'priceconsumer.FETCH_PRICECONSUMER_SUCCESS';
export const FETCH_PRICECONSUMER_FAILURE =
  'priceconsumer.FETCH_PRICECONSUMER_FAILURE';
